### ISSUE TITLE
Display time logged today and last project

### ISSUE THREAD

**Issue by mabasic** [wakatime/chrome-wakatime#10]
I think that when you click on the extension icon (popup) it should have a panel displaying the total time logged today and the latest project that you worked on.

**Comment by mabasic** [comment]
Displaying time logged today requires extra work.

**Comment by pritianka** [comment]
You could use the code from this other chrome extension someone developed
to do exactly that?  Alan, remember the one I had on my comp.  I don't
remember who built it but if it is helpful, I can find out.

Priyanka Sharma
Co-founder, WakaTime <http://www.wakatime.com> - Quantify your coding
www.twitter.com/pritianka
650-796-7125

**Comment by pritianka** [comment]
Here's what it looks like ![screen shot 2015-06-07 at 8 08 50 pm](https://cloud.githubusercontent.com/assets/2413464/8027681/0d809358-0d51-11e5-92d9-095ecf9a0f7f.png)

**Comment by mabasic** [comment]
That would be great. It would save me a lot of time.

**Comment by mabasic** [comment]
Total time logged today with all plugins implemented.
