### ISSUE TITLE
Tracking time when computer sleeping

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/chrome-wakatime#117]
Some people are experiencing a bug where the extension continuously tracks time, even when the computer is asleep. It could be this or related event handlers firing somehow when the browser has focus but the computer isn't in use:

https://github.com/wakatime/chrome-wakatime/blob/649c64cf1d18b6f6a3c00761c6bbd2d5c0c3d32d/assets/js/events.js#L14

**Comment by iesahin** [comment]
This is probably what causes multiple computers _track_ my time continuously. I was asleep until 9 am. 

![IMG_20210216_154219.jpg](https://user-images.githubusercontent.com/476310/108064440-bd068780-706d-11eb-99f9-4c81afb0ed57.jpg)

**Comment by jvelezpo** [comment]
Fixed on V3
