### ISSUE TITLE
Extension throw could not load error

### ISSUE THREAD

**Issue by longforu** [wakatime/chrome-wakatime#118]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel.

## Current Behavior

![CleanShot 2021-02-23 at 16 56 36](https://user-images.githubusercontent.com/58486890/108929012-1afc1780-75f8-11eb-8afe-7c699730707d.png)

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Latest Chrome, MacOS

**Comment by vujita** [comment]
Can you verify a few things? 
1. which version of node where you using when you did a node install
2. Did you run an npm run build first?

**Comment by jvelezpo** [comment]
Closing this, since there is a new version v3 that works with node v18, that fixes this issue
