### ISSUE TITLE
Enable blacklist

### ISSUE THREAD

**Issue by mabasic** [wakatime/chrome-wakatime#12]
Blacklist is displayed in options but is not being used in the extension.

**Comment by alanhamlett** [comment]
Notes about this from our chat:

* turn icon color grey when not recording because of blacklisted domain
* match full url against blacklist regular expressions

**Comment by mabasic** [comment]
Implemented https://github.com/wakatime/chrome-wakatime/commit/bb4fd0d1761bc762943402df9c877ab338bb86c3
