### ISSUE TITLE
adding wildcards (https://*.aws.amazon.com) to whitelist doesn't work

### ISSUE THREAD

**Issue by Ashtonian** [wakatime/chrome-wakatime#134]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel.

Wildcards don't seem to be working. 

## Expected Behavior

domain wildcards to work

## Current Behavior

it doesn't log the site

## Possible Solution

add the site by hand to whitelist 

## Steps to Reproduce
add `https://*.aws.amazon.com` to whitelist
visit https://s3.console.aws.amazon.com or https://console.aws.amazon.com/ and notice it doesn't log. 

## Context (Environment)
brave (latest)
wakatime 2.0.1

**Comment by toptalo** [comment]
Yes. Wildcards works only with black list.

**Comment by jvelezpo** [comment]
Whitelist support ready here https://github.com/wakatime/chrome-wakatime/pull/175
