### ISSUE TITLE
Build seems to be broken

### ISSUE THREAD

**Issue by muety** [wakatime/chrome-wakatime#135]
Running `npm run dev` leads to this:
![image](https://user-images.githubusercontent.com/8978843/137154604-925157a8-3117-4d4c-bccd-eae5156693d2.png)
"popup go here"

**Comment by muety** [comment]
Any news here?

**Comment by alanhamlett** [comment]
Related to #70.

**Comment by jvelezpo** [comment]
This is not broken, apparently the development stopped in the middle of a migration from JS to TS, the new TS versions has not implemented the `WakaTime.jsx` and has a dummy component in its root, we just need to finish the TS migration

**Comment by jvelezpo** [comment]
https://github.com/wakatime/chrome-wakatime/pull/153

**Comment by jvelezpo** [comment]
https://github.com/wakatime/chrome-wakatime/pull/155
