### ISSUE TITLE
Extension takes a lot of space 212MB

### ISSUE THREAD

**Issue by Yadro** [wakatime/chrome-wakatime#136]
I'm using it in Yandex Browser on macOS.

![Снимок экрана 2021-12-16 в 10 17 48](https://user-images.githubusercontent.com/3994873/146325885-d4cb9030-c1d6-4a8d-b5eb-d805fb04b910.png)

**Comment by jvelezpo** [comment]
Versions 3 shipd with a better use of disk space

![Image](https://user-images.githubusercontent.com/1050904/222307142-15da3571-44b0-443c-b21a-d2b48c8708e5.png)
