### ISSUE TITLE
Add a toggle button for disabling/enabling logging

### ISSUE THREAD

**Issue by mabasic** [wakatime/chrome-wakatime#14]
Since this logs every URL/domain, I have realized that at many times I want to disable logging because of sensitive information that URLs can contain.

**Comment by gandarez** [comment]
Great idea! Also I'm sending only the domain.

**Comment by alanhamlett** [comment]
Sure, I agree let's only send the domain.

**Comment by pritianka** [comment]
Guys - I don't completely agree on just doing domains and not full URLs.  I was actually talking about a use case yesterday where let's say someone is in QuickBooks and has different URLs for different clients, then having the full domain can show that ... thoughts?

**Comment by teserak** [comment]
Same with GMail - https://mail.google.com/mail/u/2/.

Maybe whitelist with regexp support (like: `(https://mail.google.com/mail/u/\d+/)`) - all except group 0 will be ignored.

**Comment by teserak** [comment]
You can change icon color (red/green) when toggle.

**Comment by mabasic** [comment]
@teserak When toggled on/off the icon will change normal/red.

I currently agree with @alanhamlett about only sending domains.

@pritianka There are benefits to logging full URLs, but I think that because of security issues this is not an option.

**Comment by pritianka** [comment]
Sorry, can you explain - when you say security, you mean it's literally not
possible or we don't want to do it for best practice reasons?  If we don't
want to do it, can it be up to the user to decide if he wants the full URL?

Priyanka Sharma
Co-founder, WakaTime <http://www.wakatime.com> - Time Tracking for
Programmers
www.twitter.com/pritianka
650-796-7125

**Comment by mabasic** [comment]
@pritianka This is kinda tricky to explain.

Imagine that someone has your entire browsing history. By sending full URLs WakaTime will have your entire browsing history if logging is not turned off.

Currently there is an option in the extension where you can choose between logging the full URL or only the domain. Because there is a lot of friction about this, I suggest we leave that option there and set the default to domain (as currently is).

@alanhamlett Please give the final word :)

**Comment by pritianka** [comment]
Oh awesome, if the user has the option to log the full URL should they want
to, then I am peachy!  :-)

Priyanka

Priyanka Sharma
Co-founder, WakaTime <http://www.wakatime.com> - Time Tracking for
Programmers
www.twitter.com/pritianka
650-796-7125

**Comment by alanhamlett** [comment]
@mabasic makes sense. :+1:

**Comment by mabasic** [comment]
Added button and functionality.

**Comment by gandarez** [comment]
@mabasic I reinstalled and came disabled, it should come enabled as default, don't you agree?

**Comment by mabasic** [comment]
@gandarez It should, will fix asap.
