### ISSUE TITLE
Progress is stuck to a certain project name.

### ISSUE THREAD

**Issue by MohamedMassoudSyft** [wakatime/chrome-wakatime#148]
Progress on Chrome is stuck to a certain project. Even if I am working on other project. It still registers to that certain project.
## Expected Behavior

Chrome should register progress to the current project I am working on "Along side Unity & Visual Studio Wakatime plugins"
## Current Behavior
Chrome only register progress to a certain "STUCK" project even If I am working on another project.

## Possible Solution
I am using Bengsfort Wakatime plugin for Unity. I tried to rename the stuck project to something else on Wakatime Dashboard. I think the problem started from there. 

## Steps to Reproduce
1. Start working on any project on Unity or Visual Studio.
2. Try to surf the web on Chrome Browser.
3. Chrome Browsing is Registered to a stuck project not the one I am currently working on.
4. Trying to change the project name, deleting it, merging. All didn't fix the problem.

## Context (Environment)
It makes the evaluation process of Wakatime not accurate. It registers time to the wrong project.

**Comment by alanhamlett** [comment]
Fixed now. It should log time to the last project you coded in.

**Comment by MohamedMassoudSyft** [comment]
Thank you for the instant and accurate help. It works as it should now.
