### ISSUE TITLE
The plugin logs heartbeats of the shown tag when I am away after being used for a while

### ISSUE THREAD

**Issue by ShreckYe** [wakatime/chrome-wakatime#150]
## Expected Behavior

The plugin should only log heartbeats when I am browsing a webpage, for example, when I move my mouse pointer or scroll on a webpage.

## Current Behavior

The plugin logs heartbeats of the shown tag when I am away, no matter I have Chrome in focus or minimize it. This only starts to happen after I use the WakaTime plugin for a while. When I uninstall and reinstall the plugin, the problem is gone for one or two days and then back again.

## Possible Solution

No suggestions.

## Steps to Reproduce

See Current Behavior.

## Context (Environment)

This has happened both on Ubuntu and macOS. I currently have Chrome of Version 106.0.5249.119 (Official Build) (64-bit) on Ubuntu 22.04 LTS.

## Detailed Description

No info.

## Possible Implementation

No suggestions.

**Comment by ShreckYe** [comment]
Some addtional information on Context (Environment): on Ubuntu it seems the issue only occurs with LightDM, with gdm (GNOME Display Manager) it works fine.

**Comment by oderwat** [comment]
It logs heartbeats with Opera using the Chrome Plugin too. I had to uninstall it, because I just worked 4 Hours on a project while I was not even near the computer.

**Comment by jvelezpo** [comment]
closing this
there is new version of the extension that fixed this
