### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/chrome-wakatime#152]
Bugs

1. Prevent tracking when browser not in focus. Look at last mouse x,y and make sure it's changed before sending a heartbeat.
2. Use api key instead of cookies for authentication. Change extension icon color to red if api key missing. Prompt for api key when first installed. Show currently logged in user in options menu when clicking extension icon. Edit api key in options menu.
3. Offline tracking, save heartbeats and send later when online

Features

1. Automatically detect projects based on url (github repo in url, online IDEs, etc). Currently we send
`"project":"<<LAST_PROJECT>>"`. Instead send something like, `"project":"website"` if the url is `github.com/alanhamlett/website`
2. Have pre-set lists of domains to enable tracking. For ex: let people only track coding and not other browsing. For example, a toggle that excludes all non-dev websites (`facebook.com`, `youtube.com`, ...)

**Comment by jvelezpo** [comment]
This PR https://github.com/wakatime/chrome-wakatime/pull/155 adds an input to set the apiKey

**Comment by jvelezpo** [comment]
https://github.com/wakatime/chrome-wakatime/pull/156
https://github.com/wakatime/chrome-wakatime/pull/157

**Comment by jvelezpo** [comment]
Automatically detect projects based on url (github repo in url, online IDEs, etc) https://github.com/wakatime/chrome-wakatime/pull/165/
