### ISSUE TITLE
Set current project

### ISSUE THREAD

**Issue by teserak** [wakatime/chrome-wakatime#17]
All data going to **Unknown Project**.
I want to attach data to specific project. 
If I work on **chrome-wakatime**  I want to see this data in **chrome-wakatime**.

All data in single project are useless, because I see localhost:8000 and stackoverflow.com and I don't know with which project are associated.

**Comment by alanhamlett** [comment]
So a dropdown to choose the current project? Something like [this](http://brianreavis.github.io/selectize.js/) with an option to type a custom project name.

**Comment by teserak** [comment]
Dropdown with extra project "Other activity" or something similar.

**Comment by gandarez** [comment]
Also a good one https://select2.github.io/examples.html

**Comment by gandarez** [comment]
Would be better the possibilty of specifying specific urls to projects.
http://localhost:51533 -> Project 1
http://localhost:51534 -> Project 2

For all other urls not defined above I suggest to create a group named "Chrome" or something like that.

**Comment by mabasic** [comment]
@alanhamlett Should I close this issue, since it does not belong on the extension issue list, but on wakatime dashboard?

**Comment by teserak** [comment]
@gandarez What with stackoverflow or google?

**Comment by gandarez** [comment]
@teserak didn't get your question.

**Comment by teserak** [comment]
You said, to set different ports for different projects - that's ok.
How (in the same way) - attach time for other domains (like stackoverflow) which are common ?

**Comment by gandarez** [comment]
@teserak they could set a default project that holds everything else. I haven't had thought on this.

**Comment by CodyKochmann** [comment]
Is this able to look at the other statistics being sent to Wakatime? If we have a log from five to ten minutes ago a different project was being worked on, you could link that traffic and with that project.

**Comment by mabasic** [comment]
Moving the discussion here: https://github.com/wakatime/chrome-wakatime/issues/28
