### ISSUE TITLE
Support for Figma

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/chrome-wakatime#181]
Child of #47.

When the domain is figma.com, we can detect the project based on the DOM. For example, if we find this in the DOM:

```html
<span class="filename_view--titleWithToggleContainer--aXP2c filename_view--title--Qhcgs ellipsis--ellipsis--70pHK" dir="auto" data-testid="filename" tabindex="0" role="textbox">Landing Page</span>
```

With full xpath (not reliable because it's React):
```
/html/body/div[2]/div/div/div[1]/div/div[3]/div/div[3]/div[2]/div/div/span
```

And page JavaScript variable:
```
> figma.root.name
'Landing Page'
```

Then we should detect...

Project: `Landing Page`
Language: `Figma Design`
Editor: `Figma`
Category: `Designing`

The most reliable way is probably injecting JavaScript onto the page to extract the value of `figma.root.name` and send it back to the extension's background page.

**Comment by few-bits** [comment]
@alanhamlett please review #184

**Comment by jvelezpo** [comment]
https://github.com/wakatime/chrome-wakatime/pull/185
