### ISSUE TITLE
Potential Whitelist?

### ISSUE THREAD

**Issue by CodyKochmann** [wakatime/chrome-wakatime#21]
I'm not sure about everyone else but I live my personal life through chrome as well so the blacklist would end up becoming seriously long in order to remain accurate. Maybe consider a whitelist as well? Say if I only wanted the time spent on GitHub, Cloud 9, and StackExchange. :)

**Comment by mabasic** [comment]
Both whitelist and blacklist will be implemented. You can set your preference on the extension options page.

**Comment by mabasic** [comment]
Implemented https://github.com/wakatime/chrome-wakatime/commit/bb4fd0d1761bc762943402df9c877ab338bb86c3
