### ISSUE TITLE
Issue with JEST

### ISSUE THREAD

**Issue by mabasic** [wakatime/chrome-wakatime#23]
See here: https://github.com/facebook/jest/issues/243

Just so we know about this issue and decide on what's the best solution.

**Comment by mabasic** [comment]
So this dude made it clear here https://github.com/facebook/jest/issues/243#issuecomment-108650372 that JEST 0.5 will probably come with support for node 0.12

Now we just need to find out when JEST 0.5 will be released.

**Comment by mabasic** [comment]
There is also a lot of talk here: https://github.com/facebook/jest/pull/374

I am not sure what will happen now with node.js and io.js and how will that affect JEST.

**Comment by Stephn-R** [comment]
Is it a drastic issue for us to limit the Node version to 0.10 until the Jest issue has been resolved?

**Comment by mabasic** [comment]
We can do that in Travis or similar when we setup the environment, but locally ... is anyone still using 0.10 when 0.12 is available?

I really really don't want to downgrade my local or vm installation of node.js.
