### ISSUE TITLE
<<LAST_BRANCH>> support?

### ISSUE THREAD

**Issue by ghost** [wakatime/chrome-wakatime#232]
Hi!

Thanks for making this Wakatime browser plugin!  I'm using browser-wakatime, together with Wakapi to track monthly worked hours with. This is based on hours spent on certain branch names.  Would it be feasible to have browser activity (besides to a project with <<LAST_PROJECT>>) linked  to the last branch being worked on (e.g. <<LAST_BRANCH>>? This would enable me as frontend developer. to make a much more precise hours report, since I spend quite some time tweaking a UI at http://localhost:3000 

Downstream ticket is at https://github.com/muety/wakapi/discussions/532

**Comment by alanhamlett** [comment]
Implemented with c57818bec78d7f51a26ecc20fddf85dc42ea9a84.

**Comment by jvanveen** [comment]
That's fast! :zap:
