### ISSUE TITLE
Tracks domains are not whitelisted.

### ISSUE THREAD

**Issue by rafaelstz** [wakatime/chrome-wakatime#24]
Tracks the domains that are not whitelisted , they are as unknown.

**Comment by mabasic** [comment]
Could you please explain more detailed what is the issue?

**Comment by rafaelstz** [comment]
I add only domain, and in my dashboard show all.

    Login type: Only the domain

**Comment by mabasic** [comment]
You are saying that in the options you set the extension to only log domain names and not the full URL, but in the wakatime dashboard you are seeing the full URLs ?

**Comment by rafaelstz** [comment]
No, in dashboard show others URLs.

**Comment by mabasic** [comment]
I am really having problems understanding your issue. Could you describe one step at a time what is the issue?

**Comment by rafaelstz** [comment]
I set my configuration, example: 
![sc_7-options4](https://cloud.githubusercontent.com/assets/610598/8257656/c2b7aea4-1685-11e5-85f7-d5b5e96e68b3.png)

But my **Dashboard** show and considerate all websites:

![wakatime](https://cloud.githubusercontent.com/assets/610598/8258171/467bae90-1689-11e5-9078-4df2875214da.jpg)

**Comment by mabasic** [comment]
There are several factors that can cause this:

- Did you update the extension to the latest version
- Initially the extension is set to blacklist, so maybe before you have set it to whitelist it recorded some sites

**Comment by rafaelstz** [comment]
Thanks! My version is  **1.0.0**

**Comment by mabasic** [comment]
Np, but I have only released [`0.8.3`](https://github.com/wakatime/chrome-wakatime/tree/0.8.3).

`1.0.0` is declared in the manifest file because that will be the first release that will go to chrome store.

**Comment by pritianka** [comment]
I love how, "on it" you are!  :-)
ᐧ

Priyanka Sharma
Co-founder, WakaTime <http://www.wakatime.com> - Quantify your coding
www.twitter.com/pritianka
650-796-7125
