### ISSUE TITLE
Have we considered regex?

### ISSUE THREAD

**Issue by CodyKochmann** [wakatime/chrome-wakatime#25]
Generally regex is a big no no for actual interphases but since it's a developer focused extension allowing regex in the white/blacklists it would enable us to do things like `*.edu*` could go into research or `*.coffee*` could go towards the coffeescript language.

**Comment by mabasic** [comment]
Currently the blacklist and the whitelist work on this principle:

> Take the list (blacklist/whitelist) and see if the current URL **contains** the phrase from the list. If it does, return true.

If you type in the whitelist `.edu`, then the extension would check if the current URL contains `.edu` and if it does, return true.

**Comment by CodyKochmann** [comment]
You should take out the `http://` portion of the example then, it had me adding everything twice just in case.

**Comment by mabasic** [comment]
Will do that.

**Comment by CodyKochmann** [comment]
Is it case sensitive? Just curious.

**Comment by mabasic** [comment]
Good question  :) I think that it is case sensitive, but will have to check to confirm.

**Comment by mabasic** [comment]
It is case sensitive.
