### ISSUE TITLE
ChangeExtensionState is missing a default switch case

### ISSUE THREAD

**Issue by Stephn-R** [wakatime/chrome-wakatime#26]
[See here](https://github.com/wakatime/chrome-wakatime/blob/97a5070129302538d197cc5280122d5bc6d04efd/assets/js/helpers/changeExtensionState.js#L18-L39)

**Comment by mabasic** [comment]
Since I am checking if the given state exists I already know to which switch statements I must respond.

Is the default switch case required for some reason?

**Comment by mabasic** [comment]
Here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch it says the the default switch case is optional, so I am guessing that we don't need it.
