### ISSUE TITLE
Issue with timing in currentTimestamp.js

### ISSUE THREAD

**Issue by Stephn-R** [wakatime/chrome-wakatime#27]
[Reference](https://github.com/wakatime/chrome-wakatime/blob/97a5070129302538d197cc5280122d5bc6d04efd/assets/js/helpers/currentTimestamp.js)

Why would you need to divide by 1000? When converting the timestamp back to a date variable, the time is off:

```js
// GOOD
var x = (new Date()).getTime()
>> 1434727916970

new Date(x)
>> Fri Jun 19 2015 11:31:56 GMT-0400 (Eastern Daylight Time)

// WRONG?
var y = (new Date()).getTime() / 1000

new Date(y)
>> Sat Jan 17 1970 09:32:07 GMT-0500 (Eastern Standard Time)
```

**Comment by mabasic** [comment]
I will probably replace that function with moment.js version. At the time I wrote it I did not use moment.js, but since it is already included it makes sense to use it.

**Comment by mabasic** [comment]
Replaced with `moment().format('X');`
