### ISSUE TITLE
Change to white icone when dark themed

### ISSUE THREAD

**Issue by gandarez** [wakatime/chrome-wakatime#3]
Hi!

I know is too early to ask them about it. By the way, Is it possible to change the wakatime icon to white one when using a dark theme?
![image](https://cloud.githubusercontent.com/assets/782854/7841916/21a4d0ee-0476-11e5-8d78-68a1a58d5ea7.png)

**Comment by mabasic** [comment]
Will take that into consideration.

**Comment by alanhamlett** [comment]
Probably easier to use a non-transparent icon image instead of changing the image color.

**Comment by gandarez** [comment]
@alanhamlett I think the single problem regarding this approarch is that you are keeping wakatime black one.

**Comment by mabasic** [comment]
I think that I have figured this one out. We will leave an option on options page where you can change dark theme, white theme and it's solved.

**Comment by gandarez** [comment]
@mabasic I agree.

**Comment by mabasic** [comment]
Implemented. Will be merged very soon.
