### ISSUE TITLE
prevent API request every time checkAuth is called from switching tabs

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/chrome-wakatime#30]
**Current behavior:**

A request is made to `/api/v1/users/current` when switching between tabs every time, then the heartbeat request is made to send the heartbeat if logged in.

**Should be:**

Make a request to check if authenticated only when clicking on the extension icon. Check response code from sending a heartbeat. If it's `201`, then we are logged in. If it's `401` then we are not logged in. This way we only make 1 request when sending a heartbeat, not 2 (checking if logged in and sending the actual heartbeat).

**Comment by mabasic** [comment]
That makes more sense. Nice job on noticing that. Going to implement that asap.

**Comment by mabasic** [comment]
Implemented.
