### ISSUE TITLE
How to test chrome extension API?

### ISSUE THREAD

**Issue by mabasic** [wakatime/chrome-wakatime#31]
In a function `changeExtensionTooltip` I have a line of code like this:

```
chrome.browserAction.setTitle({title: text});
```

And I want to assert that method `chrome.browserAction.setTitle` has been called once and that it has received `{title: 'WakaTime'}`.

Can someone   help with this? @Stephn-R

**Comment by Stephn-R** [comment]
Hey @mabasic, its very easy to do exactly that. Since Jest is a descendant of Jasmine, you can use the Spy tool to do this

```js
spyOn(chrome.browserAction.setTitle);
// do some stuff
expect(chrome.browserAction.setTitle).toHaveBeenCalled();
// or
expect(chrome.browserAction.setTitle).toHaveBeenCalledWith({ title: text });
```

**Comment by mabasic** [comment]
I'm still not testing `components` using Jest. I was wondering for `helpers` using Mocha and Chai?

**Comment by Stephn-R** [comment]
Gotcha. Try looking at Sinon-Chai http://chaijs.com/plugins/sinon-chai

**Comment by mabasic** [comment]
I am looking at it but nothing is happening ... going to try it out and let you know the results :)

**Comment by Stephn-R** [comment]
Would you mind if I put one together for you in the tests?

**Comment by mabasic** [comment]
That would be great.

**Comment by Stephn-R** [comment]
Check out d6b9ccf for the example

**Comment by mabasic** [comment]
@Stephn-R I have tried writing a test for [`changeExtensionTooltip`](https://github.com/wakatime/chrome-wakatime/blob/master/tests/helpers/changeExtensionTooltip.spec.js) but failed: 

I have tried reading the documentation for Sinon but they keep talking about some spies. Then I have tried reading the sinon-chrome documentation but they keep talking about creating a new page with phantomJS and injecting scripts in it. I think that that is an overkill?

http://chaijs.com/plugins/sinon-chai
http://sinonjs.org/
https://github.com/vitalets/sinon-chrome

Also I have found a topic on [StackOverflow](http://stackoverflow.com/questions/2869827/how-to-test-chrome-extensions) where they talk about running a method in a new context.

Is there a simple way of doing this? I am willing to change the code to support dependency injection or make it easier for testing/mocking somehow.

**Comment by Stephn-R** [comment]
Yes yes, that is over kill. Link me to where your code is and I can get a simple test running for you.

**Comment by mabasic** [comment]
Here is the test I wrote: https://github.com/wakatime/chrome-wakatime/blob/master/tests/helpers/changeExtensionTooltip.spec.js 


And here is the helper which I want to test: https://github.com/wakatime/chrome-wakatime/blob/master/assets/js/helpers/changeExtensionTooltip.js
