### ISSUE TITLE
Consider removing .pem files on postinstall

### ISSUE THREAD

**Issue by phated** [wakatime/chrome-wakatime#33]
This is just an aesthetic change, but the giant red messages in chrome about `.pem` files is pretty scary for people that don't understand they are just warnings.  We handle this in our chrome extensions with an npm `postinstall` hook that removes them in all the dependencies.  See https://github.com/iceddev/git-splainin/blob/master/package.json#L20 and https://github.com/iceddev/git-splainin/blob/master/gulpfile.babel.js#L41-L43 for an example.

**Comment by mabasic** [comment]
I am aware of this, but this only occurs when installing the extension in developer mode. When the extension is published on the store it won't come with node_modules directory and it won't present red messages.

**Comment by phated** [comment]
Thanks for considering it.  We had some developers working on projects that thought these were actual errors, so we added the postinstall to improve contributor workflow.

**Comment by mabasic** [comment]
If you want, you can send a PR for that.

That would be nice.

Pozdrav,

Mario Basic

http://basicit.company
________________________________
