### ISSUE TITLE
If I whitelist a site and then later blacklist it, will all data be gone?

### ISSUE THREAD

**Issue by pritianka** [wakatime/chrome-wakatime#35]
Hi there,

If I whitelist techcrunch.com but then later remove it from the list, will the past data for it be gone?

Thanks!
Priyanka

**Comment by mabasic** [comment]
The data collected until the moment you remove it from the whitelist is retained on wakatime.

Pozdrav,

Mario Basic

http://basicit.company
________________________________

**Comment by pritianka** [comment]
Thank you!
