### ISSUE TITLE
Ability to click on URLs time captured for

### ISSUE THREAD

**Issue by pritianka-zz** [wakatime/chrome-wakatime#37]
Hi - since I have enabled full URL tracking in my WakaTime, I can not recognize what exact webpage it is often.  For example, I am a heavy Google docs worker and all I see is "edit" as the title or a long URL.

I am working for a billable client right now and if I don't know what I worked on, I can't charge the right hours for it!

So if the URLs were clickable in the project or day detail page, that would be super helpful. 

![screen shot 2015-07-24 at 7 17 32 pm](https://cloud.githubusercontent.com/assets/2413464/8875708/bae6ae54-3238-11e5-919b-de632db65cf2.png)

**Comment by alanhamlett** [comment]
The default is to track `domain` not `url`, so making `docs.google.com` clickable won't help much for most users. Closing as won't fix.
