### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by vielmetti** [wakatime/chrome-wakatime#39]
I might be missing something, but the front page readme says

> Install the extension inside Chrome.

but it's not in the Chrome store. Can you update with current install instructions (e.g. do you have to do the build yourself and install in developer mode?)

**Comment by alanhamlett** [comment]
You have to click the "load unpacked extension" button in your extension settings, then choose the chrome-wakatime folder.

**Comment by santimacia** [comment]
Why not to pack and publish to chrome store?

**Comment by benmosher** [comment]
:+1: to paraphrase of @santimacia's comment: convert this issue to "pack and publish to Chrome store".

(disclaimer: I'm unfamiliar with that process, perhaps there is a blocker to doing so?)

**Comment by maca** [comment]
+1 chrome store, tad easier than loading
