### ISSUE TITLE
Request: Capture time for certain urls only

### ISSUE THREAD

**Issue by briandela** [wakatime/chrome-wakatime#4]
Hi Mario,

First off - thanks for taking the effort to build this. If you are open to PR's I'd love to help as much as I can when I free up from my current project (in around 2 weeks).

In the meantime, I wanted to put in a feature ask for the chrome extension (although you are probably already planning on doing this). It would be great if there was the ability to specify which url's would end up capturing time to report to wakatime. E.g. if I'm on https://localhost:3001 with the dev tools open, capture the time that the window is active.

Thanks again for taking the initiative and creating this extension.

Brian

**Comment by mabasic** [comment]
Hello Brian, thank you very much, it is a pleasure building something like this. So for, Alan and I have divided the tasks among us, but if we come across something that we would need help with we'll let you know.

So far, we are working on a blacklist for websites that you don't want to track. We are (I am) still a little bit unclear on this (work in progress), so I'll leave this open for now until I hear from @alanhamlett

**Comment by briandela** [comment]
Thanks for responding. In my particular case I would ideally want to track only the time when I am working in the chrome dev tools on my own projects - in those cases I know the specific urls (e.g. https://localhost:3000, https://www.barn2door.com, etc.)

I do often open the dev tools to play around on other site just to see how things were built and to learn but I personally don't count that towards "work time". 

Again, thanks for considering and please do let me know if you are accepting PR's for features. When I have time I'd gladly look at adding a whitelist feature to track time only in that list of sites.

**Comment by mabasic** [comment]
PR's are more then welcome, but at this stage there is really no need for a PR. Once we build the core functionality (recording the time spent on websites) then it will be time for adding features.

**Comment by pritianka** [comment]
ok, stupid question guys. what’s a PR?


On Thu, May 28, 2015 at 2:03 AM, Mario Bašić < notifications@github.com [notifications@github.com] > wrote:
PR's are more then welcome, but at this stage there is really no need for a PR.
Once we build the core functionality (recording the time spent on websites) then
it will be time for adding features.

—
Reply to this email directly or view it on GitHub
[https://github.com/wakatime/chrome-wakatime/issues/4#issuecomment-106240390] .[https://ci5.googleusercontent.com/proxy/OYg14XDBhb3QUl56W8MlxKbxghpW3oakWyopn420a4hrDoSls8-eN4ws3C94XGP2rgVG4IEJsD2n8nwRisegp84gDqkbhB33f3IKtPjSjBNQ1hSLLstrSASJxS964OHYGIsDlIJ8RvpltOvgv-mp1tJC8Bzu2A=s0-d-e1-ft#https://github.com/notifications/beacon/ACTTmOsA_bbn0_6dRXvri0fVAucQ26Gdks5oNtFvgaJpZM4EsXxT.gif]





Priyanka Sharma
Co-founder, WakaTime [http://www.wakatime.com] - Analytics for Programmers www.twitter.com/pritianka [http://www.twitter.com/pritianka] 650-796-7125
[https://app.mixmax.com/api/track/v2/GFRAc2YH9vlFn4AcO/IyZy9mLp5Wb1xWYkJ3bm5WY0NHQh1mchh2cyBnI/gIt92YuIWdoRXan5SesBXZyBEOjJDMkRGNwU2Y5YTMhJTOmVmY5U2NxETMwADMwADMwY2YykDM2QGO3EmY5EjMyM2Y2QGZlJTZmV2NiFGO3YmMzITM2IWNxQTOwkDO4kzMkRjMwAzK5xGclJnI/ISZtlGdhtWY31SZt9mcoN2Ll1Wa0F2ahdnI?sc=false]

**Comment by mabasic** [comment]
PR = Pull Request

When someone wants to contribute to your project by adding features or fixing bugs then they fork the project, do the changes, commit and push them to that forked repository and then they send the original repository a PR to include those changes.

Then the original repository owner/developer can accept & merge that PR or he can close that PR without merging if he feels that the PR is not agreeing with the project.

I hope that that explains it.

**Comment by alanhamlett** [comment]
Whitelists are nice, but I'm sure I will forget to log time on some websites and will be frustrated that I can't retroactively see how long I worked.

I think blacklists are better, with good UI for handling cases where we need the user to confirm they want to log time on a site. For example, if you open dev tools on a new website we could open a notification that disappears after 6 seconds. The notification could say, "You're logging time on this site. [Prevent logging this domain in the future]".

**Comment by rodweb** [comment]
> Whitelists are nice, but I'm sure I will forget to log time on some websites and will be frustrated that I can't retroactively see how long I worked.

I guess both whitelists and blacklists will find their users, so it'd be great to implement both features to make tracking flexible. As for me, I'd like to only track time I spend in our team's bug/issue tracker and Google Docs.

**Comment by alanhamlett** [comment]
@rodweb you're right, we should have both. I just want the default set to ignore the whitelist so we don't have tons of support requests saying the extension is broken.

**Comment by mabasic** [comment]
After some messing around with the extension I have realized that logging everything (whole URL) can be a security problem for the users. See here: https://github.com/wakatime/chrome-wakatime/issues/14

My current opinion on this is that there should only be a whitelist of the URLs that you want to track/log. That way it's much safer.

Now there are two options:

1. whitelist + popup for each and every site you visit asking you to add it to whitelist
2. blacklist + only domain logging + toggle button to disable logging/tracking

**Comment by mabasic** [comment]
See here: https://github.com/wakatime/chrome-wakatime/issues/21#issuecomment-111712084
