### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by pekapa** [wakatime/chrome-wakatime#44]
I have downloaded the v1.0.2 from the Chrome Store but my extension keeps showing the red logo and asking to log in whenever I click on it.

Clicking on the log in button it opens the wakatime website where I'm already logged in.
I've tried logging out of the website and logging in again from the extension with no success.
Also tried restarting chrome and even my computer, both with no success either.

Any suggestions?

**Comment by ure** [comment]
For me it works on the workstation where i initially installed this but not on another one

**Comment by ethaizone** [comment]
Me too. Just logout once and try to login later. It's not work. Re-install chrome extension don't work too.

**Comment by vysinsky** [comment]
same here

**Comment by vysinsky** [comment]
Found a solution:

- go to https://api.wakatime.com/api/v1/users/current/heartbeats - it will probably return `Unauthorized`
- use [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en) and delete cookies from `api.wakatime.com`
- open https://wakatime.com/dashboard
- refresh api page - it should show `Missing date.` now and you should be logged in by extension

**Comment by drm-code** [comment]
@vysinsky You are a monster dude, it worked perfect bro thanks a lot

**Comment by alanhamlett** [comment]
Thanks @vysinsky! 8ae8474e3ac68cf30edf49216f113fac4a09fbbf should fix this.

**Comment by orgoj** [comment]
Need to delete cookies from https://wakatime.com/ too, to signup working. After password change. Before I have only github login.

**Comment by devkinetic** [comment]
I had same problem as above and vysinsky's solution worked perfectly

**Comment by lex111** [comment]
Reauthentication helped for me - came out of WakaTime site and logged in again.

**Comment by intari** [comment]
No 'Edti this cookie' extension needed - just clear cookies for wakatime.com using Chrome's Developer Tools.

**Comment by ethanmay** [comment]
I was able to reproduce this issue by using Chrome with multiple profiles set up (top right corner of the browser). If I have two Chrome windows open, signed in to separate profiles on each, and I sign into Wakatime in both then they both fail API authentication and will not track my time. Would be great to be able to have multiple sessions running without losing time tracking capabilities.

Note - it seems that pausing time tracking in one window, and resuming tracking in the other window will prevent Wakatime's connection from breaking.

**Comment by rdewolff** [comment]
Had to do your described steps @vysinsky twice for the plugin to work 😲

**Comment by NeuroPastor** [comment]
> Found a solution:
> 
> * go to https://api.wakatime.com/api/v1/users/current/heartbeats - it will probably return `Unauthorized`
> * use [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en) and delete cookies from `api.wakatime.com`
> * open https://wakatime.com/dashboard
> * refresh api page - it should show `Missing date.` now and you should be logged in by extension
> 
> What I remember:
> 
> * I was changing my account email and password recently
> * I was also changing API key for my account

new url [https://wakatime.com/api/v1/users/current/heartbeats](https://wakatime.com/api/v1/users/current/heartbeats)

**Comment by mvaljento** [comment]
Tracking from Chrome plugin not showing up at the website. How do I set which account I'm using?

**Comment by ampersand-dev** [comment]
thankyou very match

**Comment by alanhamlett** [comment]
Closed with #71.
