### ISSUE TITLE
Doesn't correctly track tab changes in multiple windows

### ISSUE THREAD

**Issue by rummik** [wakatime/chrome-wakatime#46]
Opening two windows in Chrome and navigating in both results in just the active tab from the first window being logged

**Comment by NicksIdeaEngine** [comment]
Came here to report this same issue.

I have it set up to track my time in CodePen.

If I move the CodePen tab out of the first window and into its own, tracking stops.

If I focus on a separate window while CodePen is active on the first window, tracking continues even if I'm browsing reddit in the second window.

I'm using Chrome (version 53 but I don't think updating to 54 will fix this) on Windows 10.

**Comment by Xunnamius** [comment]
This issue still exists today. All of my activity is logged under the same tab URL even though I have a good 400 tabs open. It's not a big deal (I stuff all my browser activity into one project using custom rules) at the moment but if the active tab changes to a different URL, it'll break my custom rule that targets that URL.

It'd be nice to be able to just set a single project name that all Chrome activity is logged to in the extension's settings :) (related: #64 #47)
