### ISSUE TITLE
chrome's deleted , dashboard's editors can see ..

### ISSUE THREAD

**Issue by monsterLin** [wakatime/chrome-wakatime#52]
In the chrome wakatime deleted, why in the DashBoard or Editors can see chrome

**Comment by alanhamlett** [comment]
You've uninstalled the Chrome extension but still see Chrome listed on your dashboard?

**Comment by monsterLin** [comment]
@alanhamlett yes...

**Comment by alanhamlett** [comment]
You see Chrome activity for days after you uninstalled the extension? The past coding activity will still be on your dashboard, but no new activity should be generated after uninstalling the Chrome extension.
