### ISSUE TITLE
Warn user if not logged in to wakatime

### ISSUE THREAD

**Issue by bendavis78** [wakatime/chrome-wakatime#55]
It had been a while since I logged into wakatime, and I had since nuked my chrome profile. I still sync'd my extensions, so chrome-wakatime was reinstalled. Today I logged in on the website because I needed to know how much time was spent a few weeks ago on a site. I incorrectly assumed that the extension was happily logging my site visits, but since I wasn't logged into the website it wasn't doing anything. It would be good if the extension warned about not being logged in (otherwise it's dead weight).

**Comment by alanhamlett** [comment]
Closed with #71.
