### ISSUE TITLE
Activity logged in wrong project 

### ISSUE THREAD

**Issue by Gianlu01** [wakatime/chrome-wakatime#56]
I'm getting an issue where the activity on chrome is logged as activity on jetbrains editors. In fact I can see urls mixed with files in the entities logged from AndroidStudio.

**Comment by alanhamlett** [comment]
This is the intended functionality. Since we can't currently detect your project based on browsing activity alone, we assign browsing activity to the last project worked in from an IDE.

More info in #28 and #47.
