### ISSUE TITLE
nothing logging in wakatime

### ISSUE THREAD

**Issue by dking3876** [wakatime/chrome-wakatime#60]
I have been attempting to use this the past few days, and nothing logs in my dashboard on wakatime. please help

**Comment by alanhamlett** [comment]
Are there any error messages or failed network requests in the extension's Dev Console?

**Comment by dking3876** [comment]
There are no console errors save:
Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools

**Comment by mchavarriae** [comment]
I have the same problem today, nothing is logging and there is not disable/enable option

**Comment by anilcancakir** [comment]
I have same today.

**Comment by toptalo** [comment]
Hello, have this in console
![image](https://user-images.githubusercontent.com/2378757/38419770-4f16117a-39aa-11e8-97c4-f45212c90a4b.png)

When I click on `Login` it opens https://wakatime.com/dashboard in new tab

**Comment by alanhamlett** [comment]
This is a temporary solution: https://github.com/wakatime/chrome-wakatime/issues/44#issuecomment-251362887

**Comment by jvelezpo** [comment]
Closing this, v3 address this issue already
