### ISSUE TITLE
Manually setting current project being worked on

### ISSUE THREAD

**Issue by itsaphel** [wakatime/chrome-wakatime#64]
Not sure if this is already possible...

Can you manually set the project you're currently working on?

So, any of the whitelisted sites whilst logging is enabled will be associated with the project that the logging has been enabled for.

Comes in useful since I might be browsing generically, for example the Stripe API docs, but if I'm browsing them for project X for example, this specific browsing time should be assigned to project X. I may need to browse them again for project Y, and the only way to really distinguish which I'm browsing for is if I can manually set what project I'm currently working on.

**Comment by alanhamlett** [comment]
Related to #47.
