### ISSUE TITLE
Google Config Sync & RegEx/Wildcard URL Filter Request

### ISSUE THREAD

**Issue by boxsnake** [wakatime/chrome-wakatime#66]
I am wondering if there is any of following features:

* Sync extension options with Google Account logged in
    * Thus I do not have to reconfig in a new computer, just logged into Google Account and sync
    * By now, when I have lots of blacklist/whitelist rules, I have to save the rules on somewhere and copied from new computer.
* RegEx or Wildcard URL Filter to blacklist/whitelist rules
    * For example, if I want `http://php.net` and `https://php.net` domains, I prefer `https?://php.net` rather than add two rules
    * Moreover, if I want `https://travis-ci.org` and `https://travis-ci.com`, I prefer `https://travis-ci.(org|com)` since both are TravisCI sites.
    * What's more, I prefer to use regex or wildcards in subdomain matching. If I want to whitelist a domain with many subdomains, I prefer not to write a long full list of it.

Consider these features requests, thanks.

**Comment by toptalo** [comment]
My PR #65 fit this issue
