### ISSUE TITLE
Sometimes not all of the extension menu is visible

### ISSUE THREAD

**Issue by SimonBrazell** [wakatime/chrome-wakatime#68]
When clicking the extension icon sometimes it appears to be shifted up so that the upper portion of the menu is not visible:

![screen shot 2018-05-06 at 4 04 28 pm](https://user-images.githubusercontent.com/16571951/39670404-6ba5acd8-5147-11e8-8677-469ed08e27e9.png)

Seems to only happen intermittently though.

Chrome Version 66.0.3359.139 (Official Build) (64-bit)
macOS High Sierra 10.13.4

**Comment by alanhamlett** [comment]
That's because `state.loggedIn` is set async, and that button component changes depending on the value of `state.loggedIn`:
https://github.com/wakatime/chrome-wakatime/blob/84d74344e703dae678cdadaab627885796f32e8e/assets/js/components/WakaTime.jsx#L62

**Comment by ciembor** [comment]
@alanhamlett Enabling or disabling time logging shouldn't be dependent on internet connection. Only synchronising data should be dependent on a `loggedIn` state. Sometimes server is down, but it doesn't mean I can't log my work time and push it to the server later.

**Comment by alanhamlett** [comment]
Yes, we should add offline coding as a feature same as the editor plugins.

**Comment by ciembor** [comment]
Any progress in this topic?

**Comment by franzos** [comment]
This is crucial. Oftentimes an unreliable internet connection, results in large gaps in time tracking.

**Comment by jvelezpo** [comment]
Closing this, 
v3 already supports:
* Extension menu visible fixed
* Offline tracking
