### ISSUE TITLE
401 errors on Heartbeats

### ISSUE THREAD

**Issue by kayhantolga** [wakatime/chrome-wakatime#72]
I noticed some 401 errors when I checked with fiddler.

https://api.wakatime.com/api/v1/users/current/heartbeats

req:
{"entity":"chrome://newtab","type":"domain","time":"1540804343","project":"<<LAST_PROJECT>>","is_debugging":false,"plugin":"chrome-wakatime/1.0.2"}
resp:
{"error":"Unauthorized"}

**Comment by Eeems** [comment]
You may need to clear cookies for api.wakatime.com, and then log out and back in.

**Comment by alanhamlett** [comment]
Closed with #71.
