### ISSUE TITLE
Wakatime Extension failing to track time accurately on Jupyter Notebook (Ubuntu 18.04)

### ISSUE THREAD

**Issue by HP-Nunes** [wakatime/chrome-wakatime#73]
Hi,

I've ran the Wakatime Extension in Chrome before, and it used to track my time spent on Jupyter Notebook just fine; however back then I was on Windows 8, and I've fully transitioned to Linux since then.

I was struggling to even get the extension to track time until I tried whitelisting the following (only the domain):

> http://localhost:8888/tree

However on my Dashboard it is not recording the language I'm working with (Python for the most part) nor is it even attributing it to the project I'm working on (I've tried whitelisting the whole url of the notebook I'm working on as a last ditch effort but nothing is being recorded).

What am I missing?

**Comment by zodiacfireworks** [comment]
Same problem report here. :wave: 

Wakatime on google chrome is not tracking nothing about localhost even when is allowed to track all sites.

I'm working on Linux Deepin based on Debian.

**Comment by naknode** [comment]
Same here on Ubuntu 20.04. Most of the time it works but a lot of times it does not.

**Comment by HP-Nunes** [comment]
There's no point in keeping this option open. Wakatime's just wack on Ubuntu. Hopefully it will work better on later releases.
