### ISSUE TITLE
Chrome web store contains old version (1.0.2 from ~30.06.2016)

### ISSUE THREAD

**Issue by mareolan** [wakatime/chrome-wakatime#77]
Chrome web store contains old version (1.0.2 from ~30.06.2016) so features like assigning URL to a specific project using @@ doesn't work (#76).

Any plans on updating the extension?

**Comment by aravindvnair99** [comment]
@mareolan As per https://github.com/wakatime/chrome-wakatime/releases, it's latest.

**Comment by AndreasNel** [comment]
Could we maybe please get a new release and a Chrome web store update so that we can use features like #76 and #65 ?

**Comment by alanhamlett** [comment]
Just submitted v2.0.0 for review today.
