### ISSUE TITLE
Unknown hostname in reports

### ISSUE THREAD

**Issue by VadVergasov** [wakatime/chrome-wakatime#87]
All reports from chrome extension are from unknown hostname. Is there any method to set hostname? Or there is no such option?

**Comment by ABHISHEK-G0YAL** [comment]
Isn't that .cgf file used by vscode extension of wakatime.
My chrome extension is the one reporting unknown hostname, and also I am on windows if you can give me path of .cfg file used by chrome extension in windows.

**Comment by VadVergasov** [comment]
> Yes you can set a custom `hostname` for it. Add `hostname = something` under `[settings]` section into `~/.wakatime.cfg`.

It doesn't work. I'm using VS Code extension and it is using this file, but on Windows 10 Home x64 1909 with Chrome 83 extension isn't using this file.

**Comment by Ettapp** [comment]
Same need here, on Ubuntu 20.04 and Chrome 87.0.4280.88; It does not seems possible to set the hostname in the extension options, resulting in the "Unkown hostname" machine in the reports...

**Comment by dimateos** [comment]
Did not found any `wakatime.cfg` in the chrome extension folder. Also searched a bit for some kind of "hostname" in the files but I found nothing either. Really would like a host name option :)
