### ISSUE TITLE
Fix this extension

### ISSUE THREAD

**Issue by wocar** [wakatime/chrome-wakatime#89]
I like wakatime but i cant believe that this extension hasn't been updated for 2 years.

can we have either build instructions to build it myself (i cant get to build it in macos) or can we have the latest version published to the extension store 

:@

**Comment by wocar** [comment]
Please @alanhamlett

**Comment by wocar** [comment]
@Eeems @danez Guys can you at least show me to build the extension. Im using MacOS Catalina and the build fails following the instructions, i tried a lot of things and i couldnt build it....

Can someone help me out publishing the latest version or showing me how to build the extension. Thank you.

**Comment by wocar** [comment]
@ecrider

**Comment by Eeems** [comment]
It's been a long time since I've touched this. I believe you just need to follow the build instructions in the readme and then use [web-ext build](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-build) to create an extension zip.

**Comment by alanhamlett** [comment]
Yes, these build instructions should be working. If not let me know and I'll help work through it:
https://github.com/wakatime/chrome-wakatime#development-instructions

We haven't forgotten about this extension, and will get it updated eventually. Currently, our top priorities are:

1. Rewriting the plugin cores from Python to Go for improved reliability and performance
2. Getting the WakaTime Desktop app (built with Electron) to v1.0 for improving plugin installation, upgrades, and detection & debugging of any plugin errors. Also, quick access to your stats via system tray icon.
3. Improving the Chrome & Firefox extensions with smarter project detection, and more options for configuring it's behavior.

**Comment by karladler** [comment]
What is the problem with just releasing the current version in the Chrome store?

**Comment by alanhamlett** [comment]
Released the current version in Chrome Web Store.
