### ISSUE TITLE
Is Wakatime designed to be used as a hammer for management?

### ISSUE THREAD

**Issue by teckel12** [wakatime/chrome-wakatime#90]
I'm curious if Wakatime was designed to be used to micro-manage a team of coders.  It seems like that's the logical use, but I don't really get that vibe from the literature, which sounds more like a social programming competition.

**Comment by alanhamlett** [comment]
https://wakatime.com/blog/1-why-i-built-wakatime

**Comment by teckel12** [comment]
So designed as a self-monitoring tool, but now being used as a micro-managing club.

**Comment by alanhamlett** [comment]
No, WakaTime it's for micro-managing. A quote from our team FAQ explains it best:

> How is developer privacy protected?
We build for the individual developer first. For example, developers can keep all their projects hidden by default and only show certain projects to the team. Team dashboards can be set fully anonymous, where only aggregate time is shown without attributing time to any individual.

https://wakatime.com/teams#common-questions

**Comment by teckel12** [comment]
Developers don't have that option if it's mandated and controlled by club-wielding management.  Basically, developers have no control to do what you suggest as that results in termination.

**Comment by alanhamlett** [comment]
> it's being used as a micro-manager's weapon

The Team dashboards were built for companies who were already time tracking for billing clients, improving estimates, or classroom settings. In those uses where dev and management goals are aligned, it makes time tracking less painful for everyone. We don't want to support bad micro-management practices, but I'm not sure how we can prevent using tools in unintended ways. For ex: Jira, Asana, Trello, Pivotal, Zube etc can all be used to micro-manage if the manager chooses.

I'd be open to ways we can prevent WakaTime being used to micro-manage, such as warnings in-product when certain guardrails are triggered. Any ideas along those lines?

**Comment by teckel12** [comment]
@alanhamlett I believe the problem (and at the same time the power) with Wakatime is it's granular information.  It doesn't just report: "Project X was worked on for 40 hours", but instead: "Project X was 32 hours browsing, 2 hour coding, 6 hours debugging".  Managers are looking at this information as you're only actually programming for 2 hours, which then took you 6 hours to correct because you wrote it incorrectly, and 32 hours just staring at your screen not doing anything.

This causes management to look at which files you were spending your time on, and then you need to explain why so many hours were spend on file X when you were tasked to be developing file Y.  Of course, when developing file Y you needed to refer to file X, but the reports just show you were not doing what you were tasked to do.

I'm not sure what the solve is for this, as dumbing the product down would really be the only way to resolve Wakatime being used in this way.  I was more asking if the intended use was to micro-manage, and if not, maybe that can be considered going forward.  Knowing it's being used incorrectly as a club instead of a useful tool may offer insight into future development.

Thanks again for your time.

**Comment by alanhamlett** [comment]
How do we define micro-management? Maybe we can put something in the terms of service agreement to prevent WakaTime being used in unintended ways.

The ideal use is a team already tracking their time for external client projects, and WakaTime automates that existing work. The wrong use case IMO is teams working on internal projects without existing time tracking. That's when using WakaTime to measure value of team contributions or to enforce 8 hour work days crosses a line of using WakaTime the wrong way.
