### ISSUE TITLE
WakaTime sometimes fails to start tracking the day on Ubuntu 20.04

### ISSUE THREAD

**Issue by naknode** [wakatime/chrome-wakatime#92]
I use WakaTime (v1.0.2) for my job and I have a Ubuntu 20.04 machine with Chrome installed. (Version 84.0.4147.135 (Official Build) (64-bit))

I notice that my browsing time on whitelisted sites does not get tracked. They sometimes start getting tracked after a while but I've been doing everything to get it to restart... (logout/login, disable logging -> start logging, etc.) and nothing.

**Comment by shumoapp** [comment]
Same here on Lubuntu with Chrome 65.0.3325.181. I think it has something to do with the whitelist, because when I reset it, it starts tracking normally again.

**Comment by naknode** [comment]
@shumoapp How do you reset it?

**Comment by shumoapp** [comment]
Hi, I just remove the whitelisted sites, and select the default "All except blacklisted sites" (where the list is empty). 
Or better, just reinstall the Chrome plugin.

**Comment by toptalo** [comment]
Hello! I have noticed that heartbeats from chrome plugin count in specified project (via @@project name in plugin config) only after I have change local files in that project.

After I have change local file I can see heartbeats from chrome plugin on timeline. Like changes from local IDE opens/enables project till next day. On next day I need to edit local file again to seem my time.

**Comment by jvelezpo** [comment]
Closing this, v3 of the extension fixes this issue
