### ISSUE TITLE
Whitelist of WakaTime Not Work

### ISSUE THREAD

**Issue by Hephaest** [wakatime/chrome-wakatime#94]
Currently, I set a host domain in order to record my Jupyter Notebook but I found it doesn't work at all.

Version 1.0.2

**Comment by llinfeng** [comment]
Instead of logging 0 minutes, the following setting logs more hours than the time I spent "actively" tinkering with Jupyter notebooks. I am also with Version 1.0.2.

![image](https://user-images.githubusercontent.com/5890407/100943886-1974f480-34cc-11eb-991f-943c3f311bda.png)

**Comment by alanhamlett** [comment]
Can you try loading the extension from source code, using master branch of this repo?

**Comment by marcopollacci** [comment]
> Can you try loading the extension from source code, using master branch of this repo?

Hi, there are any updated instruction to build project?

**Comment by llinfeng** [comment]
@marcopollacci Thank you for asking what was my initial response. I finally got motivated to give it a try after two weeks.

For now, well, just don't bother with building it quite yet. The extension in the master branch does not do much :) It has an empty option field. My notes for building the project are at the bottom, after the divider.

![image](https://user-images.githubusercontent.com/5890407/108529174-3686bb80-72a2-11eb-859b-33d37ad2a4da.png)

-----

These are based on a similar note for Firefox, posted in issue #49, per [this post](https://github.com/wakatime/chrome-wakatime/issues/49#issuecomment-782160405).
```
# 1. clone this repo
# 2. cd to the folder
# 3. get `npm` ready: otherwise, I get `clap not found` error
npm install
# 4. build the extension locally
npm start
# Should things compile, finally, you can try to "load" the following directory via Developer mode
# Path: /chrome-wakatime/dist/chrome
```
Note the following:
1.  These steps worked on a Linux Mint machine, but not on a WSL Pengwin instance. I installed `npm` through `conda` on both machines.
2. The Developer mode thing does not with Chrome from Google. I used Vivaldi instead. (Ref: https://superuser.com/a/768154)

**Comment by vujita** [comment]
Sorry, I'll add some notes to the readme later. That is instructions for the new build path.

The released version is just sourcing it from the repo folder

**Comment by marcopollacci** [comment]
I'll looking for the new instruction, thank you :)

**Comment by llinfeng** [comment]
@vujita Could you speak of the "OPTIONS GO HERE" in the screenshot, and when will it be fixed if it is a bug (or produced by an unpushed commit)?

**Comment by vujita** [comment]
![image](https://user-images.githubusercontent.com/1197701/108546790-76e43a80-729e-11eb-9670-681b43733399.png)

The current production build is from assets, and builds to the repo level folder.

The future build from _src_ and will go into _dist_, this is still in the works

**Comment by llinfeng** [comment]
I don't quite follow what you said. Could you detail the steps for "production build"? I have no idea how to deal with the two folders in [`assets/`](https://github.com/wakatime/chrome-wakatime/tree/master/assets).

**Comment by vujita** [comment]
The published extension source code is in [assets](https://github.com/wakatime/chrome-wakatime/tree/master/assets)
This will build the js/css to a git ignored [public folder](https://github.com/wakatime/chrome-wakatime/blob/master/manifest.json#L3).
Then you load the extension from the same folder as the repo, not dist

The next build will build into a dist folder, and will be sourced from there. I am in the middle of porting it over and want to leave what is currently released untouched

**Comment by llinfeng** [comment]
Sounds good (though, it still did not get me to try what @alanhamlett was suggesting in the first place).

Nevertheless, looking forward to a new release. Here is a running list of problems I have encountered:
1. With a whitelisted tab loaded in a tab, when I leave the browser window, the timer keeps counting the idle hours. 
2. Need a pointer to "load the extension from source code".

**Comment by jvelezpo** [comment]
Solved on V3 👍
